# Homework 6, Part One: Lots and lots of questions about beer

### Do your importing and your setup

In [9]:
import pandas as pd

/Users/chandrimachatterjee/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pandas/compat/__init__.py:109: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

## Read in the file `craftcans.csv`, and look at the first first rows

In [10]:
df = pd.read_csv("craftcans.csv")

In [4]:
df.head()

,Beer,Brewery,Location,Style,Size,ABV,IBUs
0,Get Together,NorthGate Brewing,"Minneapolis, MN",American IPA,16 oz.,4.50%,50
1,Maggie's Leap,NorthGate Brewing,"Minneapolis, MN",Milk / Sweet Stout,16 oz.,4.90%,26
2,Wall's End,NorthGate Brewing,"Minneapolis, MN",English Brown Ale,16 oz.,4.80%,19
3,Pumpion,NorthGate Brewing,"Minneapolis, MN",Pumpkin Ale,16 oz.,6.00%,38
4,Stronghold,NorthGate Brewing,"Minneapolis, MN",American Porter,16 oz.,6.00%,25

## How many rows do you have in the data? What are the column types?

In [11]:
df.tail()

,Beer,Brewery,Location,Style,Size,ABV,IBUs
2411,Mama's Little Yella Pils,Oskar Blues Brewery,"Longmont, CO",Czech Pilsener,12 oz.,5.30%,35
2412,GUBNA Imperial IPA,Oskar Blues Brewery,"Longmont, CO",American Double / Imperial IPA,12 oz.,9.90%,100
2413,Old Chub,Oskar Blues Brewery,"Longmont, CO",Scottish Ale,12 oz.,8.00%,35
2414,Gordon Ale (2009),Oskar Blues Brewery,"Longmont, CO",American Double / Imperial IPA,12 oz.,8.70%,85
2415,Dale's Pale Ale,Oskar Blues Brewery,"Longmont, CO",American Pale Ale (APA),12 oz.,6.50%,65

In [12]:
#there are 2416 rows of data
df.columns

Index(['Beer', 'Brewery', 'Location', 'Style', 'Size', 'ABV', 'IBUs'], dtype='object')

# Checking out our alcohol

## What are the top 10 producers of cans of beer?

In [13]:
df.dtypes

Beer        object
Brewery     object
Location    object
Style       object
Size        object
ABV         object
IBUs        object
dtype: object

In [14]:
df.Brewery.value_counts().head(10)

Brewery Vivant                62
Oskar Blues Brewery           46
Sun King Brewing Company      38
Cigar City Brewing Company    25
Sixpoint Craft Ales           24
Hopworks Urban Brewery        23
Stevens Point Brewery         22
Great Crescent Brewery        20
21st Amendment Brewery        20
Bonfire Brewing Company       19
Name: Brewery, dtype: int64

## What is the most common ABV? (alcohol by volume)

In [15]:
df.ABV.value_counts().head(1)

5.00%    215
Name: ABV, dtype: int64

## Oh, weird, ABV isn't a number. Convert it to a number for me, please.

It's going to take a few steps!

### First, let's just look at the ABV column by itself

In [16]:
df.ABV

0       4.50%
1       4.90%
2       4.80%
3       6.00%
4       6.00%
        ...
2411    5.30%
2412    9.90%
2413    8.00%
2414    8.70%
2415    6.50%
Name: ABV, Length: 2416, dtype: object

### Hm, `%` isn't part of  a number. Let's remove it.

When you're confident you got it right, save the results back into the `ABV` column.

- *Tip: In programming the easiest way to remove something is to *replacing it with nothing*.
- *Tip: "nothing" might seem like `NaN` sinc we talked about it a lot in class, but in this case it isn't! It's just an empty string, like ""*
- *Tip: `.replace` is used for replacing ENTIRE cells, while `.str.replace` is useful for replacing PARTS of cells (see my New York example)*

In [17]:
df.ABV = df['ABV'].str.replace("%", "")

### Now let's turn `ABV` into a numeric data type

Save the results back into the `ABV` column (again), and then check `df.dtypes` to make sure it worked.

- *Tip: We used `.astype(int)` during class, but this has a decimal in it...*

In [18]:
df.ABV

0       4.50
1       4.90
2       4.80
3       6.00
4       6.00
        ...
2411    5.30
2412    9.90
2413    8.00
2414    8.70
2415    6.50
Name: ABV, Length: 2416, dtype: object

In [19]:
df.ABV = df.ABV.astype(float)

In [20]:
df.dtypes

Beer         object
Brewery      object
Location     object
Style        object
Size         object
ABV         float64
IBUs         object
dtype: object

## What's the ABV of the average beer look like?

### Show me in two different ways: one command to show the `median`/`mean`/etc, and secondly show me a chart

In [21]:
df.ABV.median()

5.6

In [22]:
df.ABV.mean()

5.977342419080068

In [23]:
df.ABV.describe()

count    2348.000000
mean        5.977342
std         1.354173
min         0.100000
25%         5.000000
50%         5.600000
75%         6.700000
max        12.800000
Name: ABV, dtype: float64

### We don't have ABV for all of the beers, how many are we missing them from?

- *Tip: You can use `isnull()` or `notnull()` to see where a column is missing data.*
- *Tip: You just want to count how many `True`s and `False`s there are.*
- *Tip: It's a weird trick involving something we usually use to count things in a column*

In [24]:
df.ABV.isnull().value_counts()

False    2348
True       68
Name: ABV, dtype: int64

# Looking at location

Brooklyn used to produce 80% of the country's beer! Let's see if it's still true.

## What are the top 10 cities in the US for canned craft beer?

In [25]:
df.Location.value_counts().head(10)

Grand Rapids, MI    66
Chicago, IL         55
Portland, OR        52
Indianapolis, IN    43
San Diego, CA       42
Boulder, CO         41
Denver, CO          40
Brooklyn, NY        38
Seattle, WA         35
Longmont, CO        33
Name: Location, dtype: int64

## List all of the beer from Brooklyn, NY

In [35]:
df[df.Location == 'Brooklyn, NY']

,Beer,Brewery,Location,Style,Size,ABV,IBUs
115,4Beans,Sixpoint Craft Ales,"Brooklyn, NY",Baltic Porter,12 oz.,10.0,52
210,Jammer,Sixpoint Craft Ales,"Brooklyn, NY",Gose,12 oz. Slimline,4.2,16
246,Abigale,Sixpoint Craft Ales,"Brooklyn, NY",Belgian Pale Ale,12 oz.,8.0,Does not apply
404,Nomader Weiss,Evil Twin Brewing,"Brooklyn, NY",Berliner Weissbier,12 oz.,4.0,Does not apply
421,Rad,Sixpoint Craft Ales,"Brooklyn, NY",Fruit / Vegetable Beer,16 oz.,3.2,7
439,Molotov Lite,Evil Twin Brewing,"Brooklyn, NY",American Double / Imperial IPA,16 oz.,8.5,Does not apply
588,Bengali,Sixpoint Craft Ales,"Brooklyn, NY",American IPA,"24 oz. ""Silo Can""",6.5,62
713,Sensi Harvest,Sixpoint Craft Ales,"Brooklyn, NY",American Pale Ale (APA),12 oz.,4.7,50
969,Hi-Res,Sixpoint Craft Ales,"Brooklyn, NY",American Double / Imperial IPA,12 oz.,9.9,111
987,KelSo Nut Brown Lager,KelSo Beer Company,"Brooklyn, NY",Euro Dark Lager,12 oz.,5.7,19
1057,Global Warmer,Sixpoint Craft Ales,"Brooklyn, NY",American Strong Ale,12 oz.,7.0,70
1074,Autumnation (2013),Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.7,74
1093,KelSo India Pale Ale,KelSo Beer Company,"Brooklyn, NY",American IPA,12 oz.,6.0,64
1267,The Crisp,Sixpoint Craft Ales,"Brooklyn, NY",German Pilsener,16 oz.,5.4,42
1268,Sweet Action,Sixpoint Craft Ales,"Brooklyn, NY",Cream Ale,16 oz.,5.2,34
1269,Righteous Ale,Sixpoint Craft Ales,"Brooklyn, NY",Rye Beer,16 oz.,6.3,57
1270,Bengali Tiger,Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.4,62
1305,KelSo Pilsner,KelSo Beer Company,"Brooklyn, NY",Czech Pilsener,12 oz.,5.5,23
1365,Hipster Ale (Two Roads Brewing),Evil Twin Brewing,"Brooklyn, NY",American Pale Ale (APA),12 oz.,5.5,Does not apply
1366,Bikini Beer,Evil Twin Brewing,"Brooklyn, NY",American IPA,12 oz.,2.7,Does not apply
1373,East India Pale Ale,Brooklyn Brewery,"Brooklyn, NY",English India Pale Ale (IPA),16 oz.,6.8,47
1624,3Beans,Sixpoint Craft Ales,"Brooklyn, NY",Baltic Porter,12 oz.,9.9,85
1836,Brownstone,Sixpoint Craft Ales,"Brooklyn, NY",American Brown Ale,16 oz.,5.9,47
1857,Brooklyn Summer Ale,Brooklyn Brewery,"Brooklyn, NY",English Pale Mild Ale,12 oz.,4.5,Does not apply
1962,Hipster Ale (Westbrook Brewing),Evil Twin Brewing,"Brooklyn, NY",American Pale Ale (APA),12 oz.,5.5,Does not apply
1970,Apollo,Sixpoint Craft Ales,"Brooklyn, NY",American Pale Wheat Ale,16 oz.,5.2,11
1971,Harbinger,Sixpoint Craft Ales,"Brooklyn, NY",Saison / Farmhouse Ale,16 oz.,4.9,35
1972,Resin,Sixpoint Craft Ales,"Brooklyn, NY",American Double / Imperial IPA,12 oz.,9.1,103
2027,East India Pale Ale,Brooklyn Brewery,"Brooklyn, NY",English India Pale Ale (IPA),12 oz.,6.8,47
2062,Diesel,Sixpoint Craft Ales,"Brooklyn, NY",American Stout,16 oz.,6.3,69
2074,Autumnation (2011-12) (2011),Sixpoint Craft Ales,"Brooklyn, NY",Pumpkin Ale,16 oz.,6.0,48
2140,The Crisp (2011),Sixpoint Craft Ales,"Brooklyn, NY",German Pilsener,16 oz.,5.4,42
2141,Sweet Action (2011),Sixpoint Craft Ales,"Brooklyn, NY",Cream Ale,16 oz.,5.2,34
2142,Righteous Ale (2011),Sixpoint Craft Ales,"Brooklyn, NY",Rye Beer,16 oz.,6.3,57
2143,Bengali Tiger (2011),Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.4,62
2219,Brooklyn Summer Ale (2011),Brooklyn Brewery,"Brooklyn, NY",English Pale Mild Ale,12 oz.,4.5,Does not apply
2350,Brooklyn Lager (16 oz.),Brooklyn Brewery,"Brooklyn, NY",American Amber / Red Lager,16 oz.,5.2,Does not apply
2351,Brooklyn Lager (12 oz.),Brooklyn Brewery,"Brooklyn, NY",American Amber / Red Lager,12 oz.,5.2,Does not apply

## What brewery in Brooklyn puts out the most cans of beer?

In [68]:
df[df.Location == 'Brooklyn, NY'].sort_values('Brewery')
#It's Sixpoint Craft Ales but I'm having a hard time counting

,Beer,Brewery,Location,Style,Size,ABV,IBUs
2351,Brooklyn Lager (12 oz.),Brooklyn Brewery,"Brooklyn, NY",American Amber / Red Lager,12 oz.,5.2,Does not apply
2219,Brooklyn Summer Ale (2011),Brooklyn Brewery,"Brooklyn, NY",English Pale Mild Ale,12 oz.,4.5,Does not apply
2027,East India Pale Ale,Brooklyn Brewery,"Brooklyn, NY",English India Pale Ale (IPA),12 oz.,6.8,47
1857,Brooklyn Summer Ale,Brooklyn Brewery,"Brooklyn, NY",English Pale Mild Ale,12 oz.,4.5,Does not apply
1373,East India Pale Ale,Brooklyn Brewery,"Brooklyn, NY",English India Pale Ale (IPA),16 oz.,6.8,47
2350,Brooklyn Lager (16 oz.),Brooklyn Brewery,"Brooklyn, NY",American Amber / Red Lager,16 oz.,5.2,Does not apply
1962,Hipster Ale (Westbrook Brewing),Evil Twin Brewing,"Brooklyn, NY",American Pale Ale (APA),12 oz.,5.5,Does not apply
1366,Bikini Beer,Evil Twin Brewing,"Brooklyn, NY",American IPA,12 oz.,2.7,Does not apply
1365,Hipster Ale (Two Roads Brewing),Evil Twin Brewing,"Brooklyn, NY",American Pale Ale (APA),12 oz.,5.5,Does not apply
439,Molotov Lite,Evil Twin Brewing,"Brooklyn, NY",American Double / Imperial IPA,16 oz.,8.5,Does not apply
404,Nomader Weiss,Evil Twin Brewing,"Brooklyn, NY",Berliner Weissbier,12 oz.,4.0,Does not apply
987,KelSo Nut Brown Lager,KelSo Beer Company,"Brooklyn, NY",Euro Dark Lager,12 oz.,5.7,19
1093,KelSo India Pale Ale,KelSo Beer Company,"Brooklyn, NY",American IPA,12 oz.,6.0,64
1305,KelSo Pilsner,KelSo Beer Company,"Brooklyn, NY",Czech Pilsener,12 oz.,5.5,23
210,Jammer,Sixpoint Craft Ales,"Brooklyn, NY",Gose,12 oz. Slimline,4.2,16
2143,Bengali Tiger (2011),Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.4,62
2142,Righteous Ale (2011),Sixpoint Craft Ales,"Brooklyn, NY",Rye Beer,16 oz.,6.3,57
2141,Sweet Action (2011),Sixpoint Craft Ales,"Brooklyn, NY",Cream Ale,16 oz.,5.2,34
2140,The Crisp (2011),Sixpoint Craft Ales,"Brooklyn, NY",German Pilsener,16 oz.,5.4,42
2074,Autumnation (2011-12) (2011),Sixpoint Craft Ales,"Brooklyn, NY",Pumpkin Ale,16 oz.,6.0,48
2062,Diesel,Sixpoint Craft Ales,"Brooklyn, NY",American Stout,16 oz.,6.3,69
246,Abigale,Sixpoint Craft Ales,"Brooklyn, NY",Belgian Pale Ale,12 oz.,8.0,Does not apply
1972,Resin,Sixpoint Craft Ales,"Brooklyn, NY",American Double / Imperial IPA,12 oz.,9.1,103
1971,Harbinger,Sixpoint Craft Ales,"Brooklyn, NY",Saison / Farmhouse Ale,16 oz.,4.9,35
1970,Apollo,Sixpoint Craft Ales,"Brooklyn, NY",American Pale Wheat Ale,16 oz.,5.2,11
421,Rad,Sixpoint Craft Ales,"Brooklyn, NY",Fruit / Vegetable Beer,16 oz.,3.2,7
1836,Brownstone,Sixpoint Craft Ales,"Brooklyn, NY",American Brown Ale,16 oz.,5.9,47
1624,3Beans,Sixpoint Craft Ales,"Brooklyn, NY",Baltic Porter,12 oz.,9.9,85
588,Bengali,Sixpoint Craft Ales,"Brooklyn, NY",American IPA,"24 oz. ""Silo Can""",6.5,62
713,Sensi Harvest,Sixpoint Craft Ales,"Brooklyn, NY",American Pale Ale (APA),12 oz.,4.7,50
1270,Bengali Tiger,Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.4,62
1269,Righteous Ale,Sixpoint Craft Ales,"Brooklyn, NY",Rye Beer,16 oz.,6.3,57
1268,Sweet Action,Sixpoint Craft Ales,"Brooklyn, NY",Cream Ale,16 oz.,5.2,34
1267,The Crisp,Sixpoint Craft Ales,"Brooklyn, NY",German Pilsener,16 oz.,5.4,42
1074,Autumnation (2013),Sixpoint Craft Ales,"Brooklyn, NY",American IPA,16 oz.,6.7,74
1057,Global Warmer,Sixpoint Craft Ales,"Brooklyn, NY",American Strong Ale,12 oz.,7.0,70
969,Hi-Res,Sixpoint Craft Ales,"Brooklyn, NY",American Double / Imperial IPA,12 oz.,9.9,111
115,4Beans,Sixpoint Craft Ales,"Brooklyn, NY",Baltic Porter,12 oz.,10.0,52

## What are the five most popular styles of beer produced by Sixpoint?

In [70]:
df[df['Brewery'] == 'Sixpoint Craft Ales'].head(5)

,Beer,Brewery,Location,Style,Size,ABV,IBUs
115,4Beans,Sixpoint Craft Ales,"Brooklyn, NY",Baltic Porter,12 oz.,10.0,52
210,Jammer,Sixpoint Craft Ales,"Brooklyn, NY",Gose,12 oz. Slimline,4.2,16
246,Abigale,Sixpoint Craft Ales,"Brooklyn, NY",Belgian Pale Ale,12 oz.,8.0,Does not apply
421,Rad,Sixpoint Craft Ales,"Brooklyn, NY",Fruit / Vegetable Beer,16 oz.,3.2,7
588,Bengali,Sixpoint Craft Ales,"Brooklyn, NY",American IPA,"24 oz. ""Silo Can""",6.5,62

## List all of the breweries in New York state.

- *Tip: We want to match *part* of the `Location` column, but not all of it.*
- *Tip: Watch out for `NaN` values! You might be close, but you'll need to pass an extra parameter to make it work without an error.*

### Now *count* all of the breweries in New York state

# Measuring International Bitterness Units

## Display all of the IPAs

Include American IPAs, Imperial IPAs, and anything else with "IPA in it."

IPA stands for [India Pale Ale](https://www.bonappetit.com/story/ipa-beer-styles), and is probably the most popular kind of beer in the US for people who are drinking [craft beer](https://www.craftbeer.com/beer/what-is-craft-beer).

IPAs are usually pretty hoppy and bitter. IBU stands for [International Bitterness Unit](http://www.thebrewenthusiast.com/ibus/), and while a lot of places like to brag about having the most bitter beer (it's an American thing!), IBUs don't necessary *mean anything*.

Let's look at how different beers have different IBU measurements.

## Try to get the average IBU measurement across all beers

### Oh no, it doesn't work!

It looks like some of those values *aren't numbers*. There are two ways to fix this:

1. Do the `.replace` and `np.nan` thing we did in class. Then convert the column to a number. This is boring.
2. When you're reading in your csv, there [is an option called `na_values`](http://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.read_csv.html). You can give it a list of **numbers or strings to count as `NaN`**. It's a lot easier than doing the `np.nan` thing, although you'll need to go add it up top and run all of your cells again.

- *Tip: Make sure you're giving `na_values` a LIST, not just a string*

### Now try to get the average IBUs again

## Draw the distribution of IBU measurements, but with *twenty* bins instead of the default of 10

- *Tip: Every time I ask for a distribution, I'm looking for a histogram*
- *Tip: Use the `?` to get all of the options for building a histogram*
- *Tip: Make sure your `matplotlib` thing is set up right!*

## Hm, Interesting distribution. List all of the beers with IBUs above the 75th percentile

- *Tip: There's a single that gives you the 25/50/75th percentile*
- *Tip: You can just manually type the number when you list those beers*

## List all of the beers with IBUs below the 25th percentile

## List the median IBUs of each type of beer. Graph it.

Put the highest at the top, and the missing ones at the bottom.

- Tip: Look at the options for `sort_values` to figure out the `NaN` thing. The `?` probably won't help you here.

## Hmmmm, it looks like they are generally different styles. What are the most common 5 styles of high-IBU beer vs. low-IBU beer?

- *Tip: You'll want to think about it in three pieces - filtering to only find the specific beers beers, then finding out what the most common styles are, then getting the top 5.*
- *Tip: You CANNOT do this in one command. It's going to be one command for the high and one for the low.*
- *Tip: "High IBU" means higher than 75th percentile, "Low IBU" is under 25th percentile*

## Get the average IBU of "Witbier", "Hefeweizen" and "American Pale Wheat Ale" styles

I'm counting these as wheat beers. If you see any other wheat beer categories, feel free to include them. I want ONE measurement and ONE graph, not three separate ones. And 20 to 30 bins in the histogram, please.

- *Tip: I hope that `isin` is in your toolbox*

## Draw a histogram of the IBUs of those beers

## Get the average IBU of any style with "IPA" in it (also draw a histogram)

## Plot those two histograms on top of one another

To plot two plots on top of one another, you do two steps.

1. First, you make a plot using `plot` or `hist`, and you save it into a variable called `ax`.
2. You draw your second graph using `plot` or `hist`, and send `ax=ax` to it as a parameter.

It would look something like this:

```python
ax = df.plot(....)
df.plot(ax=ax, ....)
``` 

(...except totally different)

## Compare the ABV of wheat beers vs. IPAs : their IBUs were really different, but how about their alcohol percentage?

Wheat beers might include witbier, hefeweizen, American Pale Wheat Ale, and anything else you think is wheaty. IPAs probably have "IPA" in their name.

## Good work!

If you made it this far you deserve a drink.